Refs/heads/40 vista wordle
VerneDevelopers/TriatGames pull request #52
Opened 2024-02-04 12:14 UTC by CasadoManuelJesus

Vista del Wordle con pagina, componentes y sus respectivas clases CSS.

2024-02-04 18:19 UTC, bernat13 requested changes
Me falta en esta vista, un input donde poner la palabra y un mensaje de intentalo mañana, la pal,abra de hoy era... y un mensaje de enhorabuena. has acertado!

ah, 1 una fila de como se ve si la palabra aun no ha sido intentada.

solo veo filas de palabras ya jugadas. pero no de las filas en gris o deshabilitadas indicando que esos intentos aun te quedan.

son dos tonterias para cambiar mañana antes de fusionar el pull request.

2024-02-06 20:37 UTC, bernat13 approved these changes
perfe!

2024-02-06 20:39 UTC, bernat13 commented
conflictos resueltos

2024-02-07 11:00 UTC, parerod approved these changes
Que si manu que si

2024-02-07 11:00 UTC, merged